## Знакомство с библиотеками для анализа данных. NumPy

Результат лабораторной работы − отчет в формате ноутбука Jupyter (ipynb-файл). Постарайтесь сделать ваш отчет интересным рассказом, последовательно отвечающим на вопросы из заданий. Помимо ответов на вопросы, в отчете так же должен быть код, однако чем меньше кода, тем лучше всем: нам − меньше проверять, вам —  проще найти ошибку или дополнить эксперимент. При проверке оценивается четкость ответов на вопросы, аккуратность отчета и кода.

### О задании

Лабораторные работы "NumPy" и "Pandas" направлены на работу с пакетами NumPy, Pandas и Matplotlib путём решения набора задач (да, алгебры и геометрии тут почти нет). В данных заданиях разрешено пользоваться только стандартной библиотекой языка Python, а также пакетами NumPy, Pandas и Matplotlib. Целью заданий является редактирование данного jupyter notebook-a (в части блоков с кодом на python) таким образом, чтобы были реализованы указанные в заданиях функции.


### Оценивание и штрафы

* Каждая из задач имеет определенную «стоимость» (указана в скобках около задачи)
* «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов
* Если вы нашли решение какого-то из заданий в открытом источнике, необходимо добавить ссылку на этот источник (скорее всего вы будете не единственным, кто это нашел, поэтому чтобы исключить подозрение в плагиате, необходима ссылка на источник)
* Не оцениваются задания с удалёнными формулировками
* Не оценивается лабораторная работа целиком, если она была выложена в открытый источник

###  Правила сдачи

Работу необходимо сдавать, загрузив в свой приватный репозиторий и сообщив об этом в телеграм @xrzvs (или просто открыв доступ к ноутбуку в Google Colab; более подробную информацию смотрите в README.md). 

### Знакомство с Numpy

Во всех заданиях данного ноутбука **запрещено** использовать циклы (ключевые слова *for* и *while*), [list comprehension](https://habrahabr.ru/post/30232/), [map и т.п.](http://pythonicway.com/python-functinal-programming)

Для каждой задачи приведите примеры использования реализованных функций. Без примеров баллы за задание будут снижены в 2 раза, примеры должны отличаться от тех что приведены в самом задании

Под матрицей в заданиях понимается двумерный [numpy.array](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)

In [2]:
import numpy as np

**(0.25 балла) Задание 1.** Реализуйте функцию, принимающую на вход матрицу ```X``` и два массива индексов ```indices1``` и ```indices2``` одинаковой длины и возвращающую np.array, состоящий из последовательности элементов 

```[X[indices1[0], indices2[0]], ... , X[indices1[N-1], indices2[N-1]]]```

In [51]:
def construct_array(X, indices1, indices2):
    print(X[indices1,indices2])
    return X[indices1,indices2]


assert np.allclose (construct_array(np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]), [1, 2, 3], [2, 1, 0]), np.array([6,8, 10]))
assert np.allclose (construct_array(np.zeros((4,3)), [2, 2, 0], [1, 1, 0]), np.array([0,0,0]))#мой пример

[ 6  8 10]
[0. 0. 0.]


**(0.25 балла) Задача 2.** Реализуйте функцию, которая на вход принимает два массива ```X``` и ```Y``` (массивы могут быть n-мерные, но их размерности должны совпадать), а возвращает **True** если они равны и **False** - иначе.

In [52]:
def detect_identic(X, Y):
  print((X==Y).all())
  return(X==Y).all()

assert np.allclose (detect_identic(np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]), np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 11]])), False)
assert np.allclose (detect_identic(np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]), np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])), True)
assert np.allclose (detect_identic(np.zeros((3,4)), np.ones((3,4))), False)#мой пример
assert np.allclose (detect_identic(np.zeros((3,3)), np.zeros((3,3))), True)# мой пример

False
True
False
True


**(0.25 балла) Задание 3.** Реализуйте функцию, которая на вход принимает цветное изображение ```X``` (трехмерный вектор размера (n, m, 3)) и возвращает среднее значение по трём каналам (вектор длины 3).

In [60]:
def mean_channel(X):
  X=np.array_split(X, 3, axis=2)
  print(np.array([np.mean(X[0]), np.mean(X[1]), np.mean(X[2])]))
  return np.array([np.mean(X[0]), np.mean(X[1]), np.mean(X[2])])


assert np.allclose (mean_channel(np.arange(27).reshape((3, 3, 3))), np.array([12., 13., 14.]))
assert np.allclose (mean_channel(np.arange(1,96,2).reshape((3, 4, 4))), np.array([46., 49., 51.]))#my example

[12. 13. 14.]
[46. 49. 51.]


**(0.25 балла) Задание 4. ** Реализуйте функцию, принимающую на вход матрицу ```X``` и некоторое число ```a``` и возвращающую ближайший к числу элемент матрицы.

Например, для ```X = np.arange(0,10).reshape((2, 5))``` и ```a = 3.6``` ответом будет 4.

In [68]:
def nearest_value(X, a):
  print(np.argmin(np.abs(X-a)))
  return np.argmin(np.abs(X-a))


assert np.allclose (nearest_value(np.arange(0,1000).reshape((10, 10, 10)), -1), 0)
assert np.allclose (nearest_value(np.arange(0,1000).reshape((10, 10, 10)), 160.5), 160)
assert np.allclose (nearest_value(np.arange(0,1000).reshape((10, 10, 10)), 160.6), 161)
assert np.allclose (nearest_value(np.arange(0,8000).reshape((20, 20, 20)), 64.4), 64)#my example
assert np.allclose (nearest_value(np.arange(0,27).reshape((3, 3, 3)), 160.6), 26)#my example

0
160
161
64
26


**(0.5 балла) Задача 5.** Реализуйте функцию, принимающую на вход два одномерных массива ```x``` и ```y``` и возвращающую матрицу, в которой первый массив соответствует первому столбцу матрицы, второй - второму.

В этом задании **запрещается** пользоваться операцией транспонирования и рекомедуется воспользоваться методом [reshape](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.reshape.html).

In [74]:
def construct_matrix(x, y):
    print(np.column_stack((x,y)))
    return (np.column_stack((x,y)))

    
assert np.allclose (construct_matrix(np.arange(0, 6), np.arange(6, 12)), np.array([[0, 6], [1, 7], [2, 8], [3, 9], [4, 10], [5, 11]]))
assert np.allclose (construct_matrix(np.arange(1, 8), np.arange(50, 57)), np.array([[ 1, 50],[ 2, 51],[ 3, 52],[ 4, 53],[ 5, 54],[ 6, 55],[7,56]]))#my example

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
[[ 1 50]
 [ 2 51]
 [ 3 52]
 [ 4 53]
 [ 5 54]
 [ 6 55]
 [ 7 56]]


**(0.5 балла) Задание 6.** Реализуйте функцию, которая на вход принимает вектор ```x```, содержащий целые числа, кроме 0, а возвращает вектор со вставленными нулями между числами.

Например, из ```[1, -5, 3]``` получить ```[1, 0, -5, 0, 3]```

In [73]:
def add_zeros(x):
    print(np.insert(x, range(1,len(x)),0))
    return(np.insert(x, range(1,len(x)),0))   


assert np.allclose (add_zeros(np.arange(1, 10)), np.array([1., 0., 2., 0., 3., 0., 4., 0., 5., 0., 6., 0., 7., 0., 8., 0., 9.]))
assert np.allclose (add_zeros(np.array([1])), np.array([1]))
assert np.allclose (add_zeros(np.array([])), np.array([]))
assert np.allclose (add_zeros(np.array([1, 2, 3, 4])), np.array([1, 0, 2, 0, 3, 0, 4]))#my example

[1 0 2 0 3 0 4 0 5 0 6 0 7 0 8 0 9]
[1]
[]
[1 0 2 0 3 0 4]


**(0.75 балла) Задание 7.** Реализуйте функцию для подсчёта произведения ненулевых элементов на диагонали прямоугольной матрицы

Например, для ```X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])``` ответом является 3. Если ненулевых элементов нет, функция должна возвращать ```None```.

In [80]:
def nonzero_product(X):
  if np.sum(np.diag(X)[np.diag(X) != 0])!=0 :
    a=np.prod(np.diag(X)[np.diag(X) != 0])
  else: 
      a=None
  print(a)
  return a


assert np.allclose (nonzero_product(np.array([[3, 3, 3], [5, 5, 5], [7, 7, 0]])),15)
assert nonzero_product(np.array([[0, 3, 3], [5, 0, 5], [7, 7, 0]])) == None
assert nonzero_product(np.zeros((3,3))) == None #my example
assert np.allclose (nonzero_product(4*np.ones((3,3))),64)#my example

15
None
None
64.0


**(0.75 балла) Задание 8.** Реализуйте функцию, возвращающую максимальный элемент в массиве ```X``` среди элементов, перед которыми стоит нулевой.

Например, для ```X = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])``` ответом является 5. Если подходящих элементов нет, функция должна возвращать ```None```.

In [81]:
def max_element(X):
    Y=np.append(X[1: ], -1)
    if np.prod(Y)!=0:
      a=None

    elif max(Y[X==0])==0:
      a=None
    else:
      a=max(Y[X==0])
    print(a)
    return a


assert max_element(np.array([1,2,3,4,5])) == None
assert max_element(np.array([1,0,0,0,0])) == None
assert np.allclose(max_element(np.array([1,0,3,2,0])), 3)
assert max_element(np.array([1,2,0,0,0])) == None #my example
assert np.allclose(max_element(np.array([2,3,0,4,0,3])),4)#my example
assert np.allclose(max_element(np.array([1,2,0,3,0,4,0])),4) #my example

None
None
3
None
4
4


**(0.75 балла) Задание 9.** Реализуйте функцию, принимающую на вход матрицу ```X``` и возвращающую все её уникальные строки в виде матрицы.

In [83]:
def get_unique_rows(X):
  print( np.unique(X,axis =0))
  return np.unique(X,axis =0)


assert np.allclose (get_unique_rows(np.array([[1, 2], [1, 9], [1, 2],[1, 9]])), np.array([[1, 2], [1, 9]]))
assert np.allclose (get_unique_rows(np.zeros((10,10))), np.zeros(10))
assert np.allclose (get_unique_rows(np.array([[0, 0, 0], [1, 1, 1], [1, 1, 1], [0, 0, 0]])), np.array([[0, 0, 0],[1, 1, 1]]))#my example

[[1 2]
 [1 9]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0 0 0]
 [1 1 1]]


**(0.75 балла) Задача 10.** Реализуйте функцию, которая во входной вещественной матрице ```X``` находит все значения ```nan``` и заменяет их на среднее арифметическое всех остальных элементов. Если все элементы матрицы ```nan```, то верните нулевую матрицу той же размерности.

In [85]:
def replace_nans(X):
    if np.prod(np.isnan(X))==0:
      c=np.nanmean(X)
      a=np.nan_to_num(X, copy=True, nan=c, posinf=None, neginf=None)
    else:
      a=np.nan_to_num(X, copy=True, nan=0.0, posinf=None, neginf=None)
    print(a)
    return a


assert np.allclose (replace_nans(np.array([np.nan, np.nan])), np.zeros(2))
assert np.allclose (replace_nans(np.array([[2, np.nan], [np.nan, 3]])), np.array([[2., 2.5], [2.5, 3.]]))
assert np.allclose (replace_nans(np.array([[2, 2], [3, 3]])), np.array([[2,2], [3,3]]))#my example( idk what can i add)

[0. 0.]
[[2.  2.5]
 [2.5 3. ]]
[[2 2]
 [3 3]]


**(1 балл) Задача 11.** Напишите функцию, генерирующую [матрицу Вандермонда](https://ru.wikipedia.org/wiki/Определитель_Вандермонда), принимающую на вход вектор $(x_1, ... , x_n)$.

В этом задании **запрещается** пользоваться готовыми реализациями (например, [numpy.vander](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vander.html)), а также [np.repeat](https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html) и [np.transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html).

При решении задействуйте [np.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) и/или [np.newaxis](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html).

In [87]:
def vander(x):
  if x.shape!=(0,):
    a=np.flip(np.column_stack([x ** (len(x) - 1 - i) for i in range(len(x))]), axis=1)
  else:
    a=np.array([])
  print(a)
  return a


assert np.allclose (np.vander(np.array([]), increasing=True), vander(np.array([])))
assert np.allclose (np.vander(np.array([1, 2, 3, 5]), increasing=True), vander(np.array([1, 2, 3, 5])))
assert np.allclose (np.vander(np.arange(1,7), increasing=True), vander(np.array([1, 2, 3,4,5,6])))#my example

[]
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]
[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]
 [   1    6   36  216 1296 7776]]


**(1 балл) Задача 12.** Даны две вещественные матрицы ```X``` и ```Y``` с одинаковым числом столбцов и, в общем случае, различным числом строк. Необходимо реализовать функцию, вычисляющую матрицу попарных [косинусных коэффициентов](https://en.wikipedia.org/wiki/Cosine_similarity) между всеми $X_i$ и $Y_j$, где $X_i$ - $i$-ая строка матрицы $X$, а $Y_j$ - $j$-ая строка матрицы $Y$. 

В этом задании **запрещается** пользоваться готовыми реализациями, а также [np.repeat](https://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html) и [np.transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html).

При решении задействуйте [np.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) и/или [np.newaxis](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html), [np.sqrt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sqrt.html), [np.sum](https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html) и [np.power](https://docs.scipy.org/doc/numpy/reference/generated/numpy.power.html).

In [ ]:
def count_cosine_similarity(X, Y):
    # Your code here


assert np.allclose (count_cosine_similarity(np.array([[1, 2], [4, 8], [1, 2]]), np.array([[1, 2], [4, 2]])), np.array([[1, 0.8], [1, 0.8], [1, 0.8]]))
assert np.allclose (count_cosine_similarity(np.ones((10, 5)), np.ones((3, 5))), np.ones((10, 3)))